resource "citrixadc_auditnslogaction" "action1" {
    name = "action1"
    serverip = "127.1.0.1"
    serverport = "3021"
    loglevel = ["NONE"]
    dateformat = "MMDDYYYY"
    logfacility = "LOCAL0"
    tcp = "NONE"
    acl = "DISABLED"
    timezone = "LOCAL_TIME"
    userdefinedauditlog = "NO"
    appflowexport = "DISABLED"
    lsn = "ENABLED"
    alg = "DISABLED"
    subscriberlog = "DISABLED"
    sslinterception = "DISABLED"
    urlfiltering = "DISABLED"
    contentinspectionlog = "DISABLED"
    domainresolvenow = "false"
}