package snmpalarm

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func SnmpalarmDataSourceSchema() schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
			},
			"logging": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Logging status of the alarm. When logging is enabled, the Citrix ADC logs every trap message that is generated for this alarm.",
			},
			"normalvalue": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Description: "Value for the normal threshold. A trap message is generated if the value of the respective attribute falls to or below this value after exceeding the high threshold.",
			},
			"severity": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Severity level assigned to trap messages generated by this alarm. The severity levels are, in increasing order of severity, Informational, Warning, Minor, Major, and Critical.\nThis parameter is useful when you want the Citrix ADC to send trap messages to a trap listener on the basis of severity level. Trap messages with a severity level lower than the specified level (in the trap listener entry) are not sent.",
			},
			"state": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Current state of the SNMP alarm. The Citrix ADC generates trap messages only for SNMP alarms that are enabled. Some alarms are enabled by default, but you can disable them.",
			},
			"thresholdvalue": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Description: "Value for the high threshold. The Citrix ADC generates an SNMP trap message when the value of the attribute associated with the alarm is greater than or equal to the specified high threshold value.",
			},
			"time": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Description: "Interval, in seconds, at which the Citrix ADC generates SNMP trap messages when the conditions specified in the SNMP alarm are met.Can be specified for the following alarms: SYNFLOOD, HA-VERSION-MISMATCH, HA-DISK-ENCRYPTION-MISMATCH, HA-SYNC-FAILURE, HA-NO-HEARTBEATS,HA-BAD-SECONDARY-STATE, CLUSTER-NODE-HEALTH, CLUSTER-NODE-QUORUM, CLUSTER-VERSION-MISMATCH, CLUSTER-BKHB-FAILED, PORT-ALLOC-FAILED, COMPACT-FLASH-ERRORS, HARD-DISK-DRIVE-ERRORS and APPFW traps. Default trap time intervals: SYNFLOOD and APPFW traps = 1sec, PORT-ALLOC-FAILED = 3600sec(1 hour), PORT-ALLOC-EXCEED = 3600sec(1 hour), SYSLOG-CONNECTION-DROPPED = 3600sec(1 hour), Other Traps = 86400sec(1 day)",
			},
			"trapname": schema.StringAttribute{
				Required:    true,
				Description: "Name of the SNMP alarm. This parameter is required for identifying the SNMP alarm and cannot be modified.",
			},
		},
	}
}
