package snmpalarm

import (
	"context"

	"github.com/citrix/terraform-provider-citrixadc/citrixadc_framework/utils"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

// SnmpalarmDataSourceModel is the data-source-specific model, decoupled from
// SnmpalarmResourceModel.
//
// A data source is a pure read surface (Read only; no plan/apply lifecycle), so
// it can expose the FULL GET projection: the read/write attributes (as Computed
// outputs) AND the read-only attributes the resource deliberately omits. Every
// non-key attribute is Computed; the Framework's per-attribute model <-> schema
// reflection requires this model to have exactly the attributes the data-source
// schema declares, which is why it cannot reuse the resource model.
type SnmpalarmDataSourceModel struct {
	Id             types.String `tfsdk:"id"`
	Holdtime       types.Int64  `tfsdk:"holdtime"`
	Logging        types.String `tfsdk:"logging"`
	Normalvalue    types.Int64  `tfsdk:"normalvalue"`
	Severity       types.String `tfsdk:"severity"`
	State          types.String `tfsdk:"state"`
	Thresholdvalue types.Int64  `tfsdk:"thresholdvalue"`
	Time           types.Int64  `tfsdk:"time"`
	Trapname       types.String `tfsdk:"trapname"` // Required lookup key

	// Read-only (GET-only) metadata from the NITRO doc read-only set
	// (zion73x_readonly/snmpalarm.json). Never settable; populated from GET.
	Timeout types.Int64 `tfsdk:"timeout"`
}

func SnmpalarmDataSourceSchema() schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
			},
			"holdtime": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Description: "Hold time Interval, in seconds, at which the Citrix ADC generates SNMP trap messages when the conditions specified in the SNMP alarm are met recursively for a given period of time. It is recommended to have the hold time interval period in multiple of 7 seconds as the ADC tries to validate the alarms every 7 seconds. Can only be specified for the MGMT-CPU-USAGE alarm.",
			},
			"logging": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Logging status of the alarm. When logging is enabled, the Citrix ADC logs every trap message that is generated for this alarm.",
			},
			"normalvalue": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Description: "Value for the normal threshold. A trap message is generated if the value of the respective attribute falls to or below this value after exceeding the high threshold.",
			},
			"severity": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Severity level assigned to trap messages generated by this alarm. The severity levels are, in increasing order of severity, Informational, Warning, Minor, Major, and Critical.\nThis parameter is useful when you want the Citrix ADC to send trap messages to a trap listener on the basis of severity level. Trap messages with a severity level lower than the specified level (in the trap listener entry) are not sent.",
			},
			"state": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Current state of the SNMP alarm. The Citrix ADC generates trap messages only for SNMP alarms that are enabled. Some alarms are enabled by default, but you can disable them.",
			},
			"thresholdvalue": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Description: "Value for the high threshold. The Citrix ADC generates an SNMP trap message when the value of the attribute associated with the alarm is greater than or equal to the specified high threshold value.",
			},
			"time": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Description: "Interval, in seconds, at which the Citrix ADC generates SNMP trap messages when the conditions specified in the SNMP alarm are met.Can be specified for the following alarms: SYNFLOOD, HA-VERSION-MISMATCH, HA-DISK-ENCRYPTION-MISMATCH, HA-SYNC-FAILURE, HA-NO-HEARTBEATS,HA-BAD-SECONDARY-STATE, CLUSTER-NODE-HEALTH, CLUSTER-NODE-QUORUM, CLUSTER-VERSION-MISMATCH, CLUSTER-BKHB-FAILED, PORT-ALLOC-FAILED, COMPACT-FLASH-ERRORS, HARD-DISK-DRIVE-ERRORS and APPFW traps. Default trap time intervals: SYNFLOOD and APPFW traps = 1sec, PORT-ALLOC-FAILED = 3600sec(1 hour), PORT-ALLOC-EXCEED = 3600sec(1 hour), SYSLOG-CONNECTION-DROPPED = 3600sec(1 hour), Other Traps = 86400sec(1 day)",
			},
			"trapname": schema.StringAttribute{
				Required:    true,
				Description: "Name of the SNMP alarm. This parameter is required for identifying the SNMP alarm and cannot be modified.",
			},

			// Read-only (GET-only) metadata surfaced by the data source (these are
			// intentionally NOT modeled on the resource). All Computed.
			"timeout": schema.Int64Attribute{
				Computed:    true,
				Description: "If DB is enabled and clear config is fired, then to reset timeinterval of alarm, corresponding default time value is needed. This hidden argument holds the default time value for the corresponding alarm.",
			},
		},
	}
}

// snmpalarmDataSourceSetAttrFromGet projects a NITRO snmpalarm GET response onto
// the data-source model. Because a data source has no plan/apply reconciliation,
// attributes are simply filled from the GET (or left Null when the GET omits
// them). The shared utils.MapGet* helpers implement that projection.
func snmpalarmDataSourceSetAttrFromGet(ctx context.Context, data *SnmpalarmDataSourceModel, g map[string]interface{}) {
	tflog.Debug(ctx, "In snmpalarmDataSourceSetAttrFromGet Function")

	if v, ok := g["trapname"]; ok && v != nil {
		data.Id = types.StringValue(utils.AnyToString(v))
		data.Trapname = types.StringValue(utils.AnyToString(v))
	}

	data.Holdtime = utils.MapGetInt64(g, "holdtime")
	data.Logging = utils.MapGetString(g, "logging")
	data.Normalvalue = utils.MapGetInt64(g, "normalvalue")
	data.Severity = utils.MapGetString(g, "severity")
	data.State = utils.MapGetString(g, "state")
	data.Thresholdvalue = utils.MapGetInt64(g, "thresholdvalue")
	data.Time = utils.MapGetInt64(g, "time")

	// Read-only (GET-only) metadata.
	data.Timeout = utils.MapGetInt64(g, "timeout")
}
