package snmpalarm

import (
	"context"

	"github.com/citrix/adc-nitro-go/resource/config/snmp"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/citrix/terraform-provider-citrixadc/citrixadc_framework/utils"
)

// SnmpalarmResourceModel describes the resource data model.
type SnmpalarmResourceModel struct {
	Id             types.String `tfsdk:"id"`
	Logging        types.String `tfsdk:"logging"`
	Normalvalue    types.Int64  `tfsdk:"normalvalue"`
	Severity       types.String `tfsdk:"severity"`
	State          types.String `tfsdk:"state"`
	Thresholdvalue types.Int64  `tfsdk:"thresholdvalue"`
	Time           types.Int64  `tfsdk:"time"`
	Trapname       types.String `tfsdk:"trapname"`
}

func (r *SnmpalarmResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Version: 1,
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "The ID of the snmpalarm resource.",
			},
			"logging": schema.StringAttribute{
				Optional:    true,
				Default:     stringdefault.StaticString("ENABLED"),
				Description: "Logging status of the alarm. When logging is enabled, the Citrix ADC logs every trap message that is generated for this alarm.",
			},
			"normalvalue": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Description: "Value for the normal threshold. A trap message is generated if the value of the respective attribute falls to or below this value after exceeding the high threshold.",
			},
			"severity": schema.StringAttribute{
				Optional:    true,
				Default:     stringdefault.StaticString("Unknown"),
				Description: "Severity level assigned to trap messages generated by this alarm. The severity levels are, in increasing order of severity, Informational, Warning, Minor, Major, and Critical.\nThis parameter is useful when you want the Citrix ADC to send trap messages to a trap listener on the basis of severity level. Trap messages with a severity level lower than the specified level (in the trap listener entry) are not sent.",
			},
			"state": schema.StringAttribute{
				Optional:    true,
				Default:     stringdefault.StaticString("ENABLED"),
				Description: "Current state of the SNMP alarm. The Citrix ADC generates trap messages only for SNMP alarms that are enabled. Some alarms are enabled by default, but you can disable them.",
			},
			"thresholdvalue": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Description: "Value for the high threshold. The Citrix ADC generates an SNMP trap message when the value of the attribute associated with the alarm is greater than or equal to the specified high threshold value.",
			},
			"time": schema.Int64Attribute{
				Optional:    true,
				Default:     int64default.StaticInt64(1),
				Description: "Interval, in seconds, at which the Citrix ADC generates SNMP trap messages when the conditions specified in the SNMP alarm are met.Can be specified for the following alarms: SYNFLOOD, HA-VERSION-MISMATCH, HA-DISK-ENCRYPTION-MISMATCH, HA-SYNC-FAILURE, HA-NO-HEARTBEATS,HA-BAD-SECONDARY-STATE, CLUSTER-NODE-HEALTH, CLUSTER-NODE-QUORUM, CLUSTER-VERSION-MISMATCH, CLUSTER-BKHB-FAILED, PORT-ALLOC-FAILED, COMPACT-FLASH-ERRORS, HARD-DISK-DRIVE-ERRORS and APPFW traps. Default trap time intervals: SYNFLOOD and APPFW traps = 1sec, PORT-ALLOC-FAILED = 3600sec(1 hour), PORT-ALLOC-EXCEED = 3600sec(1 hour), SYSLOG-CONNECTION-DROPPED = 3600sec(1 hour), Other Traps = 86400sec(1 day)",
			},
			"trapname": schema.StringAttribute{
				Required:    true,
				Description: "Name of the SNMP alarm. This parameter is required for identifying the SNMP alarm and cannot be modified.",
			},
		},
	}
}

func snmpalarmGetThePayloadFromtheConfig(ctx context.Context, data *SnmpalarmResourceModel) snmp.Snmpalarm {
	tflog.Debug(ctx, "In snmpalarmGetThePayloadFromtheConfig Function")

	// Create API request body from the model
	snmpalarm := snmp.Snmpalarm{}
	if !data.Logging.IsNull() {
		snmpalarm.Logging = data.Logging.ValueString()
	}
	if !data.Normalvalue.IsNull() {
		snmpalarm.Normalvalue = utils.IntPtr(int(data.Normalvalue.ValueInt64()))
	}
	if !data.Severity.IsNull() {
		snmpalarm.Severity = data.Severity.ValueString()
	}
	if !data.State.IsNull() {
		snmpalarm.State = data.State.ValueString()
	}
	if !data.Thresholdvalue.IsNull() {
		snmpalarm.Thresholdvalue = utils.IntPtr(int(data.Thresholdvalue.ValueInt64()))
	}
	if !data.Time.IsNull() {
		snmpalarm.Time = utils.IntPtr(int(data.Time.ValueInt64()))
	}
	if !data.Trapname.IsNull() {
		snmpalarm.Trapname = data.Trapname.ValueString()
	}

	return snmpalarm
}

func snmpalarmSetAttrFromGet(ctx context.Context, data *SnmpalarmResourceModel, getResponseData map[string]interface{}) *SnmpalarmResourceModel {
	tflog.Debug(ctx, "In snmpalarmSetAttrFromGet Function")

	// Convert API response to model
	if val, ok := getResponseData["logging"]; ok && val != nil {
		data.Logging = types.StringValue(val.(string))
	} else {
		data.Logging = types.StringNull()
	}
	if val, ok := getResponseData["normalvalue"]; ok && val != nil {
		if intVal, err := utils.ConvertToInt64(val); err == nil {
			data.Normalvalue = types.Int64Value(intVal)
		}
	} else {
		data.Normalvalue = types.Int64Null()
	}
	if val, ok := getResponseData["severity"]; ok && val != nil {
		data.Severity = types.StringValue(val.(string))
	} else {
		data.Severity = types.StringNull()
	}
	if val, ok := getResponseData["state"]; ok && val != nil {
		data.State = types.StringValue(val.(string))
	} else {
		data.State = types.StringNull()
	}
	if val, ok := getResponseData["thresholdvalue"]; ok && val != nil {
		if intVal, err := utils.ConvertToInt64(val); err == nil {
			data.Thresholdvalue = types.Int64Value(intVal)
		}
	} else {
		data.Thresholdvalue = types.Int64Null()
	}
	if val, ok := getResponseData["time"]; ok && val != nil {
		if intVal, err := utils.ConvertToInt64(val); err == nil {
			data.Time = types.Int64Value(intVal)
		}
	} else {
		data.Time = types.Int64Null()
	}
	if val, ok := getResponseData["trapname"]; ok && val != nil {
		data.Trapname = types.StringValue(val.(string))
	} else {
		data.Trapname = types.StringNull()
	}

	// Set ID for the resource
	// Case 2: Single unique attribute
	data.Id = types.StringValue(data.Trapname.ValueString())

	return data
}
