package admparameter

import (
	"context"

	"github.com/citrix/adc-nitro-go/resource/config/adm"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

// AdmparameterResourceModel describes the resource data model.
type AdmparameterResourceModel struct {
	Id                types.String `tfsdk:"id"`
	Admserviceconnect types.String `tfsdk:"admserviceconnect"`
}

func (r *AdmparameterResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Version: 1,
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "The ID of the admparameter resource.",
			},
			"admserviceconnect": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Parameter to enable/disable Citrix ADM Service Connect. This feature helps you discover your Citrix ADC instances effortlessly on Citrix ADM service and get insights and curated machine learning based recommendations for applications and Citrix ADC infrastructure. Possible values = ENABLED, DISABLED",
			},
		},
	}
}

func admparameterGetThePayloadFromtheConfig(ctx context.Context, data *AdmparameterResourceModel) adm.Admparameter {
	tflog.Debug(ctx, "In admparameterGetThePayloadFromtheConfig Function")

	// Create API request body from the model
	admparameter := adm.Admparameter{}
	if !data.Admserviceconnect.IsNull() && !data.Admserviceconnect.IsUnknown() {
		admparameter.Admserviceconnect = data.Admserviceconnect.ValueString()
	}

	return admparameter
}

func admparameterSetAttrFromGet(ctx context.Context, data *AdmparameterResourceModel, getResponseData map[string]interface{}) *AdmparameterResourceModel {
	tflog.Debug(ctx, "In admparameterSetAttrFromGet Function")

	// Convert API response to model
	if val, ok := getResponseData["admserviceconnect"]; ok && val != nil {
		data.Admserviceconnect = types.StringValue(val.(string))
	} else {
		data.Admserviceconnect = types.StringNull()
	}

	// NOTE: data.Id is intentionally NOT set here. To preserve backward
	// compatibility with the SDK v2 resource, the ID is the synthetic value
	// generated by Create (resource.PrefixedUniqueId("tf-admparameter-")) and
	// is carried forward from prior state on Read/Update, exactly as SDK v2 did
	// (SDK v2 read never mutated the ID).

	return data
}
