package ntpserver

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func NtpserverDataSourceSchema() schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
			},
			"autokey": schema.BoolAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Use the Autokey protocol for key management for this server, with the cryptographic values (for example, symmetric key, host and public certificate files, and sign key) generated by the ntp-keygen utility. To require authentication for communication with the server, you must set either the value of this parameter or the key parameter.",
			},
			"key": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Description: "Key to use for encrypting authentication fields. All packets sent to and received from the server must include authentication fields encrypted by using this key. To require authentication for communication with the server, you must set either the value of this parameter or the autokey parameter.",
			},
			"maxpoll": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Description: "Maximum time after which the NTP server must poll the NTP messages. In seconds, expressed as a power of 2.",
			},
			"minpoll": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Description: "Minimum time after which the NTP server must poll the NTP messages. In seconds, expressed as a power of 2.",
			},
			"preferredntpserver": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Preferred NTP server. The Citrix ADC chooses this NTP server for time synchronization among a set of correctly operating hosts.",
			},
			"serverip": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "IP address of the NTP server. Either serverip or servername must be specified.",
			},
			"servername": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Fully qualified domain name of the NTP server. Either serverip or servername must be specified.",
			},
		},
	}
}
