package ntpserver

import (
	"context"

	"github.com/citrix/adc-nitro-go/resource/config/ntp"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/citrix/terraform-provider-citrixadc/citrixadc_framework/utils"
)

// NtpserverResourceModel describes the resource data model.
type NtpserverResourceModel struct {
	Id                 types.String `tfsdk:"id"`
	Autokey            types.Bool   `tfsdk:"autokey"`
	Key                types.Int64  `tfsdk:"key"`
	Maxpoll            types.Int64  `tfsdk:"maxpoll"`
	Minpoll            types.Int64  `tfsdk:"minpoll"`
	Preferredntpserver types.String `tfsdk:"preferredntpserver"`
	Serverip           types.String `tfsdk:"serverip"`
	Servername         types.String `tfsdk:"servername"`
}

func (r *NtpserverResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Version: 1,
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "The ID of the ntpserver resource.",
			},
			"autokey": schema.BoolAttribute{
				Optional:    true,
				Computed:    true,
				Default:     booldefault.StaticBool(false),
				Description: "Use the Autokey protocol for key management for this server, with the cryptographic values (for example, symmetric key, host and public certificate files, and sign key) generated by the ntp-keygen utility. To require authentication for communication with the server, you must set either the value of this parameter or the key parameter.",
			},
			"key": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Description: "Key to use for encrypting authentication fields. All packets sent to and received from the server must include authentication fields encrypted by using this key. To require authentication for communication with the server, you must set either the value of this parameter or the autokey parameter.",
			},
			"maxpoll": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Default:     int64default.StaticInt64(10),
				Description: "Maximum time after which the NTP server must poll the NTP messages. In seconds, expressed as a power of 2.",
			},
			"minpoll": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Default:     int64default.StaticInt64(6),
				Description: "Minimum time after which the NTP server must poll the NTP messages. In seconds, expressed as a power of 2.",
			},
			"preferredntpserver": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Default:     stringdefault.StaticString("NO"),
				Description: "Preferred NTP server. The Citrix ADC chooses this NTP server for time synchronization among a set of correctly operating hosts.",
			},
			"serverip": schema.StringAttribute{
				// SDK v2: Optional + ForceNew (not Computed).
				Optional: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Description: "IP address of the NTP server.",
			},
			"servername": schema.StringAttribute{
				// SDK v2: Optional + ForceNew (not Computed).
				Optional: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Description: "Fully qualified domain name of the NTP server.",
			},
		},
	}
}

func ntpserverGetThePayloadFromtheConfig(ctx context.Context, data *NtpserverResourceModel) ntp.Ntpserver {
	tflog.Debug(ctx, "In ntpserverGetThePayloadFromtheConfig Function")

	// Create API request body from the model
	ntpserver := ntp.Ntpserver{}
	if !data.Autokey.IsNull() && !data.Autokey.IsUnknown() {
		ntpserver.Autokey = data.Autokey.ValueBool()
	}
	if !data.Key.IsNull() && !data.Key.IsUnknown() {
		ntpserver.Key = utils.IntPtr(int(data.Key.ValueInt64()))
	}
	if !data.Maxpoll.IsNull() && !data.Maxpoll.IsUnknown() {
		ntpserver.Maxpoll = utils.IntPtr(int(data.Maxpoll.ValueInt64()))
	}
	if !data.Minpoll.IsNull() && !data.Minpoll.IsUnknown() {
		ntpserver.Minpoll = utils.IntPtr(int(data.Minpoll.ValueInt64()))
	}
	if !data.Preferredntpserver.IsNull() && !data.Preferredntpserver.IsUnknown() {
		ntpserver.Preferredntpserver = data.Preferredntpserver.ValueString()
	}
	if !data.Serverip.IsNull() && !data.Serverip.IsUnknown() {
		ntpserver.Serverip = data.Serverip.ValueString()
	}
	if !data.Servername.IsNull() && !data.Servername.IsUnknown() {
		ntpserver.Servername = data.Servername.ValueString()
	}

	return ntpserver
}

// ntpserverSetAttrFromGet is the RESOURCE state setter.
// It preserves the user-configured serverip/servername identity attributes
// (SDK v2 Read deliberately left these untouched to avoid churn between the
// serverip and servername NITRO fields) and keeps the SDK v2 plain-value ID.
func ntpserverSetAttrFromGet(ctx context.Context, data *NtpserverResourceModel, getResponseData map[string]interface{}) *NtpserverResourceModel {
	tflog.Debug(ctx, "In ntpserverSetAttrFromGet Function")

	// Convert API response to model
	if val, ok := getResponseData["autokey"]; ok && val != nil {
		data.Autokey = types.BoolValue(val.(bool))
	} else if data.Autokey.IsUnknown() {
		data.Autokey = types.BoolNull()
	}
	if val, ok := getResponseData["key"]; ok && val != nil {
		if intVal, err := utils.ConvertToInt64(val); err == nil {
			data.Key = types.Int64Value(intVal)
		}
	} else if data.Key.IsUnknown() {
		data.Key = types.Int64Null()
	}
	if val, ok := getResponseData["maxpoll"]; ok && val != nil {
		if intVal, err := utils.ConvertToInt64(val); err == nil {
			data.Maxpoll = types.Int64Value(intVal)
		}
	} else if data.Maxpoll.IsUnknown() {
		data.Maxpoll = types.Int64Null()
	}
	if val, ok := getResponseData["minpoll"]; ok && val != nil {
		if intVal, err := utils.ConvertToInt64(val); err == nil {
			data.Minpoll = types.Int64Value(intVal)
		}
	} else if data.Minpoll.IsUnknown() {
		data.Minpoll = types.Int64Null()
	}
	if val, ok := getResponseData["preferredntpserver"]; ok && val != nil {
		data.Preferredntpserver = types.StringValue(val.(string))
	} else if data.Preferredntpserver.IsUnknown() {
		data.Preferredntpserver = types.StringNull()
	}

	// serverip / servername are the ForceNew identity attributes. Preserve the
	// configured value (SDK v2 parity). Only populate from the GET response when
	// both are unset (e.g. an imported resource that carries only the ID).
	serveripVal, _ := getResponseData["serverip"].(string)
	servernameVal, _ := getResponseData["servername"].(string)

	serveripEmpty := (data.Serverip.IsNull() || data.Serverip.IsUnknown() || data.Serverip.ValueString() == "")
	servernameEmpty := (data.Servername.IsNull() || data.Servername.IsUnknown() || data.Servername.ValueString() == "")
	if serveripEmpty && servernameEmpty {
		if serveripVal != "" {
			data.Serverip = types.StringValue(serveripVal)
		} else {
			data.Serverip = types.StringNull()
		}
		if servernameVal != "" {
			data.Servername = types.StringValue(servernameVal)
		} else {
			data.Servername = types.StringNull()
		}
	} else {
		// Preserve configured values; resolve any lingering unknown to null.
		if data.Serverip.IsUnknown() {
			data.Serverip = types.StringNull()
		}
		if data.Servername.IsUnknown() {
			data.Servername = types.StringNull()
		}
	}

	// SDK v2 plain-value ID: serverip if set, otherwise servername.
	if !data.Serverip.IsNull() && !data.Serverip.IsUnknown() && data.Serverip.ValueString() != "" {
		data.Id = types.StringValue(data.Serverip.ValueString())
	} else if !data.Servername.IsNull() && !data.Servername.IsUnknown() && data.Servername.ValueString() != "" {
		data.Id = types.StringValue(data.Servername.ValueString())
	}

	return data
}

// ntpserverSetAttrFromGetForDatasource is the DATASOURCE state setter. Unlike the
// resource setter it populates serverip/servername from the GET response (they are
// read-only outputs for a datasource), while preserving the queried lookup value
// when the response omits the corresponding field.
func ntpserverSetAttrFromGetForDatasource(ctx context.Context, data *NtpserverResourceModel, getResponseData map[string]interface{}) *NtpserverResourceModel {
	tflog.Debug(ctx, "In ntpserverSetAttrFromGetForDatasource Function")

	if val, ok := getResponseData["autokey"]; ok && val != nil {
		data.Autokey = types.BoolValue(val.(bool))
	} else {
		data.Autokey = types.BoolNull()
	}
	if val, ok := getResponseData["key"]; ok && val != nil {
		if intVal, err := utils.ConvertToInt64(val); err == nil {
			data.Key = types.Int64Value(intVal)
		} else {
			data.Key = types.Int64Null()
		}
	} else {
		data.Key = types.Int64Null()
	}
	if val, ok := getResponseData["maxpoll"]; ok && val != nil {
		if intVal, err := utils.ConvertToInt64(val); err == nil {
			data.Maxpoll = types.Int64Value(intVal)
		} else {
			data.Maxpoll = types.Int64Null()
		}
	} else {
		data.Maxpoll = types.Int64Null()
	}
	if val, ok := getResponseData["minpoll"]; ok && val != nil {
		if intVal, err := utils.ConvertToInt64(val); err == nil {
			data.Minpoll = types.Int64Value(intVal)
		} else {
			data.Minpoll = types.Int64Null()
		}
	} else {
		data.Minpoll = types.Int64Null()
	}
	if val, ok := getResponseData["preferredntpserver"]; ok && val != nil {
		data.Preferredntpserver = types.StringValue(val.(string))
	} else {
		data.Preferredntpserver = types.StringNull()
	}

	serveripVal, _ := getResponseData["serverip"].(string)
	servernameVal, _ := getResponseData["servername"].(string)

	// Populate serverip/servername from the response; keep the queried lookup
	// value when the response omits the corresponding field.
	if serveripVal != "" {
		data.Serverip = types.StringValue(serveripVal)
	} else if data.Serverip.IsUnknown() {
		data.Serverip = types.StringNull()
	}
	if servernameVal != "" {
		data.Servername = types.StringValue(servernameVal)
	} else if data.Servername.IsUnknown() {
		data.Servername = types.StringNull()
	}

	// Plain-value ID: serverip if set, otherwise servername.
	if !data.Serverip.IsNull() && !data.Serverip.IsUnknown() && data.Serverip.ValueString() != "" {
		data.Id = types.StringValue(data.Serverip.ValueString())
	} else if !data.Servername.IsNull() && !data.Servername.IsUnknown() && data.Servername.ValueString() != "" {
		data.Id = types.StringValue(data.Servername.ValueString())
	} else {
		data.Id = types.StringNull()
	}

	return data
}
