name: GoSec Security Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  gosec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install GoSec
        run: |
          curl -sSL https://github.com/securego/gosec/releases/download/v2.12.0/gosec_2.12.0_linux_amd64.tar.gz | tar -xz
          sudo mv gosec /usr/local/bin/

      - name: Run GoSec Scan
        run: gosec ./...
