name: Terraform Lint

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '.github/**'
      -  'scripts/**'
      - 'gitignore'

  pull_request:
    branches:
      - main
    paths-ignore:
    - 'docs/**'
    - '.github/**'
    -  'scripts/**'
    - 'gitignore'


jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go (for installing tflint)
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Install tflint
        run: |
          wget https://github.com/terraform-linters/tflint/releases/download/v0.44.1/tflint-linux-amd64.tar.gz
          tar -xvzf tflint-linux-amd64.tar.gz
          sudo mv tflint /usr/local/bin/

      - name: Run tflint recursively
        run: |
          find . -name "*.tf" | xargs tflint > tflint.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: tflint.sarif
