name: Trivy Security Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          curl -sSL https://github.com/aquasecurity/trivy/releases/download/v0.22.0/trivy_0.22.0_Linux-64bit.tar.gz -o trivy_0.22.0_Linux-64bit.tar.gz
          tar -xvzf trivy_0.22.0_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/

      - name: Run Trivy Scan
        run: trivy fs .
